name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build app
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: jdx/mise-action@v2
    - name: Build
      run: exec ./.github/build.sh
